{% set name = "plotly-resampler" %}
{% set version = "0.8.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5cac870d6d269cdd71d28def4cae310c609c02aac636c0831176188f16021f44

build:
  number: 3
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    # at the time of writing
    # numpy is globally pinned to 1.21 at build time
    # and will export constraints that will require
    # numpy 1.21 or greater at run time
    - numpy
    - pip
    - poetry-core >=1.1.0a6
  run:
    - python
    - dash >=2.2.0,<3.0.0
    - flask-cors >=3.0.10,<4.0.0
    - jupyter-dash >=0.4.2
    - python-kaleido ==0.2.1
    - orjson >=3.8.0,<4.0.0
    - pandas >=1.3.5,<2.0.0
    - plotly >=5.5.0,<6.0.0
    - trace-updater >=0.0.8

test:
  imports:
    - plotly_resampler
    - plotly_resampler.figure_resampler
    - plotly_resampler.aggregation.algorithms.lttbc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/predict-idlab/plotly-resampler
  doc_url: https://predict-idlab.github.io/plotly-resampler/
  summary: Visualizing large time series with plotly
  license: LicenseRef-plotly-resampler
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jvdd
    - thewchan
