{% set name = "plotly-resampler" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/plotly-resampler-{{ version }}.tar.gz
  sha256: de12d53b18a0ff4ff0b03aea5825aef29a57b0b89955c5f0d78251bb95ee989e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<3.11
  run:
    - dash >=2.2.0,<3.0.0
    - jupyter-dash >=0.4.1
    - lttbc >=0.2.0,<0.3.0
    - orjson >=3.6.7,<4.0.0
    - pandas >=1.3.5,<2.0.0
    - plotly >=5.6.0,<6.0.0
    - python >=3.6,<3.11
    - trace-updater >=0.0.8

test:
  imports:
    - plotly_resampler
    - plotly_resampler.downsamplers
  commands:
    - pip list | grep -E '{{ name }}\s+{{ version }}'
  requires:
    - pip
    - m2-grep  # [win]

about:
  home: https://github.com/predict-idlab/plotly-resampler
  doc_url: https://predict-idlab.github.io/plotly-resampler/
  summary: Visualizing large time series with plotly
  license: LicenseRef-plotly-resampler
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
