{% set name = "plotly-resampler" %}
{% set version = "0.7.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/plotly-resampler-{{ version }}.tar.gz
  sha256: a8e35a5d53c439f9a8a6e30ff7c0d145894ae8607d0c99c44032117c83ae3d74

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7.1,<3.11
  run:
    - dash >=2.2.0,<3.0.0
    # Listed as optional but required for base import
    - ipywidgets >=7.7.0
    - jupyter-dash >=0.4.2
    - lttbc ==0.2.0
    - orjson >=3.6.8,<4.0.0
    - pandas >=1.3.5,<2.0.0
    - plotly >=5.6.0,<6.0.0
    - python >=3.7.1,<3.11
    - trace-updater >=0.0.8

test:
  imports:
    - plotly_resampler
    - plotly_resampler.aggregation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/predict-idlab/plotly-resampler
  doc_url: https://predict-idlab.github.io/plotly-resampler/
  summary: Visualizing large time series with plotly
  license: LicenseRef-plotly-resampler
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
