{% set name = "plotly-resampler" %}
{% set version = "0.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e3f9ceeb5749de9a85d39755f50711a7d6a28eb1b284da250251c8896ccc1cfd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
  run:
    - python >=3.8.0,<4.0.0
    - plotly >=5.5.0,<7.0.0
    - dash >=2.11.0
    - pandas >=2.2.3  # [py>=313]
    - numpy >=1.14  # [py<311]
    - numpy >=1.24  # [py>=311 and py<313]
    - numpy >=2.0  # [py>=313]
    - orjson >=3.10.0,<4.0.0
    - tsdownsample >=0.1.3
  run_constrained:
    - flask_cors >=4.0.2,<5.0.0
    - python-kaleido 0.2.1

test:
  imports:
    - plotly_resampler
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/predict-idlab/plotly-resampler
  doc_url: https://predict-idlab.github.io/plotly-resampler/
  summary: Visualizing large time series with plotly
  license: LicenseRef-plotly-resampler
  license_file: LICENSE

extra:
  recipe-maintainers:
    - darynwhite
    - jvdd
    - thewchan
