{% set name = "plotly-resampler" %}
{% set version = "0.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e1063d6d00aa4aedeb8c2c204de8661751b2145fd06682cd8fead9983c9a8334

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7.1,<4.0.0
    - pip
    - poetry-core
  run:
    - python >=3.7.1,<4.0.0
    - plotly >=5.5.0,<6.0.0
    - dash >=2.9.0
    - pandas >=1
    - trace-updater >=0.0.8
    - numpy >=1.14
    - orjson >=3.8.0,<4.0.0
    - tsdownsample >=0.1.3

test:
  imports:
    - plotly_resampler
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/predict-idlab/plotly-resampler
  doc_url: https://predict-idlab.github.io/plotly-resampler/
  summary: Visualizing large time series with plotly
  license: LicenseRef-plotly-resampler
  license_file: LICENSE

extra:
  recipe-maintainers:
    - darynwhite
    - jvdd
    - thewchan
