{% set name = "plotly-resampler" %}
{% set version = "0.9.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 28d53709c8bfa8d0d4f85a0d969cbce2d2bfc00c376b8f932cd280360a5bb8cc

build:
  # tsdownsample not available for win
  skip: true  # [win]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - poetry-core
  run:
    - python
    - dash >=2.11.0,<3.0.0
    - flask-cors >=3.0.10,<4.0.0
    - jupyter-dash >=0.4.2
    - numpy >=1.14  # [py<311]
    - numpy >=1.24  # [py>=311]
    - orjson >=3.8.0,<4.0.0
    - pandas >=1
    - plotly >=5.5.0,<6.0.0
    - trace-updater >=0.0.8
    - tsdownsample ==0.1.2

    # Pip check complains about dash dependency here's to satistfy it
    - flask <2.3.0,>=1.0.4
    - werkzeug <2.3.0

test:
  imports:
    - plotly_resampler
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/predict-idlab/plotly-resampler
  doc_url: https://predict-idlab.github.io/plotly-resampler/
  summary: Visualizing large time series with plotly
  license: LicenseRef-plotly-resampler
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jvdd
    - thewchan
