schema_version: 1

context:
  name: plotly-resampler
  version: "0.11.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/plotly_resampler-${{ version }}.tar.gz
  sha256: 54ea25120ff05eb6f66c421c690ea1fe7b43708c9a868c554c8e9cb5cc33b38d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }},<4.0.0
    - plotly >=5.5.0,<7.0.0
    - dash >=2.11.0
    - pandas >=1
    - numpy >=1.14
    - orjson >=3.10.0,<4.0.0
    - tsdownsample >=0.1.3
  run_constraints:
    - flask_cors >=4.0.2,<5.0.0
    - python-kaleido 0.2.1.*

tests:
  - python:
      imports:
        - plotly_resampler
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Visualizing large time series with plotly
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/predict-idlab/plotly-resampler
  documentation: https://predict-idlab.github.io/plotly-resampler/

extra:
  recipe-maintainers:
    - darynwhite
    - jvdd
    - thewchan
